name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/Jass/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend/Jass
        run: npm ci

      - name: Build frontend
        working-directory: frontend/Jass
        run: npm run build

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Build backend
        working-directory: backend
        run: ./build.sh

      - name: Upload frontend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          source: "frontend/Jass/dist"
          target: "/var/www/Jass"

      - name: Upload backend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          source: "backend/bin/*"
          target: "/var/www/Jass/"

      - name: Restart backend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          script: |
            cd /var/www/Jass/backend
        
            if [ -f jass.pid ]; then
              kill $(cat jass.pid) || true
              sleep 2
              rm jass.pid
            fi

        
            nohup ./run.sh > jass.log 2>&1 &
            echo $! > jass.pid
